include $(GNUSTEP_MAKEFILES)/common.make

#TOOL_NAME = LogTest
#LogTest_OBJC_FILES = source.m imageDebayering.m
TOOL_NAME = Debay-O-Mat
Debay-O-Mat_OBJC_FILES = source.m imageDebayering.m memoryManagement.m colorCorrection.m cubeLut.m cubePixel.m rgbPixel.m

include $(GNUSTEP_MAKEFILES)/tool.make